version: '3'

services:

  node-app:
    container_name: ibm-sbc
    image: acid-harbor.aperto.de/smarter-banking-campaign/node-app:$VERSION
    ports:
      - "3000:3000"
    restart: always
    networks:
      backend

networks:
  backend:
    external: true